<?php
/**
 * KontorX_Config_Generate_Abstract
 * 
 * @category 	KontorX_Config
 * @package 	KontorX_Config_Generate
 * @version 	0.1.0
 * @license		GNU GPL
 * @author 		Marcin `widmogror` Habryn, widmogrod@gmail.com
 * 
 * TODO Dodac obsluge opcji
 */
abstract class KontorX_Config_Generate_Abstract {

	/**
	 * Informacyjny tekst generatora
	 *
	 */
	const INFO = 'Config generated by KontorX_Config_Generate';

	/**
	 * Przechowuje konfiguracje w formie tablicy asocjacyjnej
	 *
	 * @var array
	 */
	protected $_config = null;

	/**
	 * Konstruktor
	 *
	 * @param Zend_Config|array $config
	 * @param unknown_type $config
	 */
	public function __construct($config, $options = null) {
		// sprawdza poprawnosc przekazanego parametru
		$this->_config = $this->_prepareConfig($config);
	}
	
	/**
	 * Zwraca wygenerowany string z array lub @see Zend_Config
	 *
	 * @return string
	 */
	abstract public function generate();

	/**
	 * Zwraca konfiguracje
	 *
	 * @return array
	 */
	public function getConfig() {
		return $this->_config;
	}

	/**
	 * Zwraca wygenerowany string
	 *
	 * @return string
	 */
	final public function __toString() {
		return $this->generate();
	}

	/**
	 * Przygotowuje i sprawdza konfiguracje
	 *
	 * @param Zend_Config|array $config
	 * @return array
	 */
	protected function _prepareConfig($config) {
		if ($config instanceof Zend_Config) {
			$config = $config->toArray();
		} else
		if (!is_array($config)) {
			$message = "Config save object is not array or Zend_Config object";
			require_once 'KontorX/Config/Generate/Exception.php';
			throw new KontorX_Config_Generate_Exception($message);
		}

		return $config;
	}
}